import{W,H}from'#pixel-app';
export default{ id:'loupe',mount(app){
  const canvas=document.getElementById('loupe'),coord=document.getElementById('coord'),sizeSel=document.getElementById('loupeSize');let drawing=false;const CELL=20;let pan=null;
  function clamp(){const s=+sizeSel.value,h=Math.floor(s/2);app.state.cx=Math.max(h,Math.min(W-1-h,app.state.cx));app.state.cy=Math.max(h,Math.min(H-1-h,app.state.cy))}
  function draw(){clamp();const s=+sizeSel.value,h=Math.floor(s/2),ctx=canvas.getContext('2d');canvas.width=s*CELL;canvas.height=s*CELL;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,canvas.width,canvas.height);app.emit('loupe:background',{canvas,ctx,s,h,CELL});ctx.drawImage(app.compositor.canvas,app.state.cx-h,app.state.cy-h,s,s,0,0,s*CELL,s*CELL);ctx.strokeStyle='rgba(20,20,20,.65)';ctx.lineWidth=1;for(let i=0;i<=s;i++){const q=i*CELL+.5;ctx.beginPath();ctx.moveTo(q,0);ctx.lineTo(q,s*CELL);ctx.stroke();ctx.beginPath();ctx.moveTo(0,q);ctx.lineTo(s*CELL,q);ctx.stroke()}ctx.strokeStyle='cyan';ctx.lineWidth=2;ctx.strokeRect(h*CELL+1,h*CELL+1,CELL-2,CELL-2);coord.textContent=`x${app.state.cx} y${app.state.cy}`;app.emit('loupe:drawn',{canvas,ctx,s,h,CELL})}
  function sourcePoint(e){const r=canvas.getBoundingClientRect(),s=+sizeSel.value,h=Math.floor(s/2),lx=Math.max(0,Math.min(s-1,Math.floor((e.clientX-r.left)*s/r.width))),ly=Math.max(0,Math.min(s-1,Math.floor((e.clientY-r.top)*s/r.height)));return{x:app.state.cx-h+lx,y:app.state.cy-h+ly}}
  function moved(){draw();app.emit('loupe:moved',{x:app.state.cx,y:app.state.cy})}
  canvas.onpointerdown=e=>{e.preventDefault();drawing=true;canvas.setPointerCapture(e.pointerId);const tool=app.activeTool();if(tool?.id==='hand'){const r=canvas.getBoundingClientRect(),s=+sizeSel.value;pan={x:e.clientX,y:e.clientY,cx:app.state.cx,cy:app.state.cy,cellX:r.width/s,cellY:r.height/s};canvas.style.cursor='grabbing';return}const p=sourcePoint(e);if(tool?.id!=='picker')app.history.pushLayer();tool?.apply(app,p.x,p.y);draw()};
  canvas.onpointermove=e=>{if(!drawing)return;const tool=app.activeTool();if(tool?.id==='hand'&&pan){const dx=(e.clientX-pan.x)/pan.cellX,dy=(e.clientY-pan.y)/pan.cellY;app.state.cx=pan.cx-Math.round(dx);app.state.cy=pan.cy-Math.round(dy);moved();return}if(document.getElementById('tapOnly').checked)return;const p=sourcePoint(e);tool?.apply(app,p.x,p.y);draw()};
  function stop(){drawing=false;pan=null;canvas.style.cursor=app.activeTool()?.id==='hand'?'grab':''}canvas.onpointerup=stop;canvas.onpointercancel=stop;
  app.on('tool:changed',id=>{canvas.style.cursor=id==='hand'?'grab':'';if(id!=='hand')pan=null});
  document.getElementById('paint').onpointerdown=e=>{e.preventDefault();const r=e.currentTarget.getBoundingClientRect();app.state.cx=Math.floor((e.clientX-r.left)*W/r.width);app.state.cy=Math.floor((e.clientY-r.top)*H/r.height);moved()};
  document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const[dx,dy]=b.dataset.move.split(',').map(Number);app.state.cx+=dx;app.state.cy+=dy;moved()});sizeSel.onchange=()=>{draw();app.emit('loupe:size',+sizeSel.value)};app.on('composite:rendered',draw);app.on('layers:active',draw);app.loupe={draw};draw();app.emit('loupe:moved',{x:app.state.cx,y:app.state.cy});
}};