const fs=require('fs'),path=require('path'),assert=require('assert/strict'),http=require('http'),crypto=require('crypto');const {PNG}=require('pngjs');
(async()=>{const {applyPatches}=await import('../pixel-editor/contour/compose.mjs');const root=path.resolve(__dirname,'..'),dir=path.join(root,'pixel-editor/contour'),m=JSON.parse(fs.readFileSync(path.join(dir,'patches.json'))),raw=fs.readFileSync(path.join(root,'pixel-editor/hybrid/assets/weak.png')),p=PNG.sync.read(raw),base=new Uint8ClampedArray(p.data);assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),m.base_sha256);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'pixel-editor/png-lab/assets/kat-original.png'))).digest('hex'),m.source_sha256);const pal=new Set(m.palette.map(c=>c.join(',')));
 function components(data,foreground){let seen=new Set(),n=0;for(let i=0;i<139*208;i++){if(seen.has(i)||Boolean(data[i*4+3])!==foreground)continue;n++;let q=[i];seen.add(i);for(let k=0;k<q.length;k++){const t=q[k],x=t%139,y=Math.floor(t/139);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=y+dy,j=b*139+a;if(a<0||a>=139||b<0||b>=208||seen.has(j)||Boolean(data[j*4+3])!==foreground)continue;seen.add(j);q.push(j)}}}return n}
 for(const patch of m.patches){const i=(patch.y*139+patch.x)*4;assert.deepEqual([...base.slice(i,i+4)],patch.before);assert.ok(m.regions.some(({bounds:[x,y,w,h]})=>patch.x>=x&&patch.x<x+w&&patch.y>=y&&patch.y<y+h));assert.ok([0,255].includes(patch.after[3]));if(patch.after[3])assert.ok(pal.has(patch.after.slice(0,3).join(',')));if(patch.kind==='shape'){assert.notEqual(patch.before[3],patch.after[3]);assert.ok([-1,1].some(dx=>base[i+dx*4+3]!==base[i+3]))}else assert.equal(patch.before[3],patch.after[3])}
 assert.equal(m.regions.length,8);assert.equal(m.patches.filter(p=>p.kind==='outline').length,13);
 for(const patch of m.patches){if(patch.kind!=='outline'||patch.y>=148)continue;assert.equal(patch.before[3],255);assert.equal(patch.after[3],255);assert.ok([[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>!base[((patch.y+dy)*139+patch.x+dx)*4+3]));}
 assert.deepEqual(applyPatches(base,m,'base'),base);assert.deepEqual(applyPatches(base,m,'both',new Set(m.patches.map(p=>p.id))),base);
 for(const mode of ['outline','shape','both']){const out=applyPatches(base,m,mode);assert.equal(components(out,true),components(base,true));assert.equal(components(out,false),components(base,false));for(let i=0;i<out.length;i+=4)if(out.slice(i,i+4).some((v,k)=>v!==base[i+k]))assert.ok(m.patches.some(p=>(p.y*139+p.x)*4===i&&(mode==='both'||p.kind===mode)))}console.log('Patch fidelity, palette, edit bounds, topology and modes passed');if(process.argv.includes('--data-only'))return;
 const {chromium}=require('playwright');const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');try{res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png','.json':'application/json'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await chromium.launch({executablePath:process.env.CHROME_PATH||undefined});const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(`http://127.0.0.1:${server.address().port}/pixel-editor/contour/`);await page.waitForSelector('body[data-ready=true]');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.click('[data-mode=both]');await page.check('#marks');await page.selectOption('#reference','source');await page.selectOption('#reference','weak');const input=page.locator('[data-patch]').first(),id=await input.getAttribute('data-patch');await input.uncheck();fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/contour-mobile.png',fullPage:true});const event=page.waitForEvent('download');await page.click('#save');await (await event).saveAs('test-results/contour-export.png');const exported=PNG.sync.read(fs.readFileSync('test-results/contour-export.png'));assert.equal(exported.width,139);assert.equal(exported.height,208);assert.deepEqual(new Uint8ClampedArray(exported.data),applyPatches(base,m,'both',new Set([id])));await page.click('#restore');for(const region of m.regions){await page.selectOption('#region',region.id);assert.equal(await page.locator('[data-patch]').count(),m.patches.filter(p=>{const [x,y,w,h]=region.bounds;return p.x>=x&&p.x<x+w&&p.y>=y&&p.y<y+h}).length)}await page.selectOption('#region','shoulder_right');await page.locator('.comparison').screenshot({path:'test-results/contour-shoulder.png'});await page.selectOption('#region','right');await page.locator('.comparison').screenshot({path:'test-results/contour-right.png'});assert.deepEqual(errors,[]);console.log('Mobile controls, patch rejection, source comparison and exact overlay-free export passed')}
 finally{if(browser)await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
