const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),http=require('http');const {PNG}=require('pngjs');
(async()=>{const {compose}=await import('../pixel-editor/dress-study/compose.mjs');const root=path.resolve(__dirname,'..'),dir=path.join(root,'pixel-editor/dress-study'),m=JSON.parse(fs.readFileSync(path.join(dir,'assets/manifest.json'))),v={};assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,'assets/source.jpeg'))).digest('hex'),m.source_sha256);const pal=new Set(m.palette.map(c=>c.join(',')));
 for(const id of ['nearest','weak','outline']){const p=PNG.sync.read(fs.readFileSync(path.join(dir,`assets/${id}.png`)));assert.equal(p.width,139);assert.equal(p.height,208);v[id]=new Uint8ClampedArray(p.data);for(let i=0;i<p.data.length;i+=4){assert.ok([0,255].includes(p.data[i+3]));if(p.data[i+3])assert.ok(pal.has([...p.data.slice(i,i+3)].join(',')));assert.equal(p.data[i+3],v.nearest[i+3]);}}
 for(const p of m.patches){const i=(p.y*139+p.x)*4;assert.deepEqual([...v.weak.slice(i,i+4)],p.before);assert.equal(p.after[3],255);assert.equal(p.before[3],255);assert.ok(m.regions.some(({bounds:[x,y,w,h]})=>p.x>=x&&p.x<x+w&&p.y>=y&&p.y<y+h));assert.ok([[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>!v.weak[((p.y+dy)*139+p.x+dx)*4+3]));}
 assert.deepEqual(compose(v,m,'outline'),v.outline);assert.deepEqual(compose(v,m,'outline',new Set(m.patches.map(p=>p.id))),v.weak);assert.equal(v.weak[(85*139+82)*4+3],0,'Arm/dress negative space must be transparent');console.log('Source hash, common mask, palette, patch fidelity and negative space passed');if(process.argv.includes('--data-only'))return;
 const {chromium}=require('playwright');const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');try{res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png','.jpeg':'image/jpeg','.json':'application/json'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await chromium.launch({executablePath:process.env.CHROME_PATH||undefined});const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(`http://127.0.0.1:${server.address().port}/pixel-editor/dress-study/`);await page.waitForSelector('body[data-ready=true]');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/dress-mobile.png',fullPage:true});await page.selectOption('#region','straps');await page.locator('.comparison').screenshot({path:'test-results/dress-straps.png'});await page.selectOption('#reference','weak');await page.click('[data-mode=outline]');await page.selectOption('#region','all');await page.check('#marks');await page.locator('details').first().locator('summary').click();const input=page.locator('[data-patch]').first(),id=await input.getAttribute('data-patch');await input.uncheck();const ev=page.waitForEvent('download');await page.click('#save');await (await ev).saveAs('test-results/dress-export.png');const out=PNG.sync.read(fs.readFileSync('test-results/dress-export.png'));assert.deepEqual(new Uint8ClampedArray(out.data),compose(v,m,'outline',new Set([id])));await page.selectOption('#reference','cutout');await page.click('[data-mode=nearest]');assert.deepEqual(errors,[]);console.log('Mobile comparison, mode changes, patch rejection and exact PNG export passed')}
 finally{if(browser)await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
