// Functional checks with the native Canvas renderer. This is not a browser layout test.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {createCanvas,Image}=require('@napi-rs/canvas');
const html=fs.readFileSync(path.join(__dirname,'../pixel-editor/try-on/index.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
class Element{constructor(){this.disabled=true;this.textContent='';this.children=[];this.clientWidth=354;this.clientHeight=542;this.style={setProperty(){}};this.classList={toggle(){}};this.files=[]}setAttribute(k,v){this[k]=v}replaceChildren(...v){this.children=v}appendChild(){}remove(){}click(){this.onclick?.()}matches(){return false}}
const store=new Map();
function setup(){const els=new Map();const document={querySelector(s){if(!els.has(s))els.set(s,s==='#view'?Object.assign(createCanvas(96,256),{setAttribute(){}}):new Element());return els.get(s)},createElement(type){return type==='canvas'?createCanvas(96,256):new Element()},querySelectorAll(){return [...els.values()].filter(e=>e.disabled)},addEventListener(){},body:new Element()};
const context=vm.createContext({console,document,Image,ResizeObserver:class{constructor(fn){this.fn=fn}observe(){this.fn()}},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},FileReader:class{readAsDataURL(f){this.result='data:image/png;base64,'+f.bytes.toString('base64');this.onload()}},URL:{createObjectURL(){return 'blob:test'},revokeObjectURL(){}},Uint8Array});vm.runInContext(script,context);return {context,els,run:s=>vm.runInContext(s,context)}}
async function loaded(p){for(let i=0;i<100;i++){if(p.run('ready'))return;await new Promise(r=>setTimeout(r,10))}throw Error('Initialization failed')}
(async()=>{let p=setup();await loaded(p);assert.equal(p.els.get('#name').textContent,'Каре · фиолетовая прядь');assert.equal(p.run('items.length'),4);p.els.get('#next').click();assert.match(p.els.get('#name').textContent,/красная/);p=setup();await loaded(p);assert.match(p.els.get('#name').textContent,/красная/);
p.els.get('#bare').click();const pixels=()=>p.els.get('#view').getContext('2d').getImageData(0,0,96,256).data;const base=new Uint8ClampedArray(pixels());p.run('choose(1)');const composite=pixels();const mask=p.run("(()=>{const c=blank();c.getContext('2d').drawImage(items[1].image,0,0);return c.getContext('2d').getImageData(0,0,96,256).data})()");for(let i=0;i<base.length;i+=4)if(!mask[i+3])assert.deepEqual(Array.from(composite.slice(i,i+4)),Array.from(base.slice(i,i+4)));
p.els.get('#bare').click();p.els.get('#prev').click();assert.equal(p.els.get('#counter').textContent,'4 / 4');
const bytes=p.run('HAIR').split(',')[1];const buf=Buffer.from(bytes,'base64');const file={name:'custom.png',size:buf.length,bytes:buf,slice:(a,b)=>({arrayBuffer:async()=>Uint8Array.from(buf.subarray(a,b)).buffer})};await p.els.get('#upload').onchange({target:{files:[file],value:''}});assert.equal(p.els.get('#counter').textContent,'5 / 5');assert.equal(p.els.get('#name').textContent,'custom');const wrong=createCanvas(1,1).toBuffer('image/png');const bad={...file,name:'wrong.png',bytes:wrong,slice:(a,b)=>({arrayBuffer:async()=>Uint8Array.from(wrong.subarray(a,b)).buffer})};await p.els.get('#upload').onchange({target:{files:[bad],value:''}});assert.match(p.els.get('#status').textContent,/96 × 256/);assert.equal(p.run('items.length'),5);
const result=p.els.get('#view').toBuffer('image/png');const image=new Image();image.src=result;assert.equal(image.width,96);assert.equal(image.height,256);assert(base.some((v,i)=>i%4===3&&v===0));console.log('PASS: initialization, cyclic arrows, saved selection, exact body pixels, custom PNG import, wrong-size rejection, export dimensions and transparency.');})().catch(e=>{console.error(e);process.exit(1)});
