import {compose} from './compose.mjs';
const $=id=>document.getElementById(id),names={nearest:'Обычное уменьшение',weak:'PixelOE слабое',outline:'PixelOE + обводка',source:'Исходный JPEG',cutout:'Приблизительная маска'};
const crops={dress:{name:'Наряд целиком',crop:[40,43,50,79]},straps:{name:'Бретели и лиф',crop:[46,44,39,30]},hem:{name:'Складки и подол',crop:[41,72,48,50]},all:{name:'Вся Катя',crop:[29,0,73,208]}};
let meta,variants={},images={},mode='weak',disabled=new Set();const result=document.createElement('canvas');result.width=139;result.height=208;const ctx=result.getContext('2d');
function load(url){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=url})}
function crop(c,img,rect){const[x,y,w,h]=rect;c.width=w*8;c.height=h*8;const g=c.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(img,x*img.width/139,y*img.height/208,w*img.width/139,h*img.height/208,0,0,c.width,c.height)}
function render(){const data=compose(variants,meta,mode,disabled);ctx.putImageData(new ImageData(data,139,208),0,0);const g=$('whole').getContext('2d');g.clearRect(0,0,139,208);g.drawImage(result,0,0);const reg=crops[$('region').value];crop($('before'),images[$('reference').value],reg.crop);crop($('after'),result,reg.crop);$('before-label').textContent=names[$('reference').value];$('after-label').textContent=names[mode];
 const enabled=mode==='outline'?meta.patches.filter(p=>!disabled.has(p.id)):[];$('status').textContent=`139 × 208 · ${names[mode]} · ${enabled.length} правок из ${meta.patches.length}`;
 if($('marks').checked){const[x,y,w,h]=reg.crop,g=$('after').getContext('2d');g.strokeStyle='#ffcf32';g.lineWidth=2;for(const p of enabled)if(p.x>=x&&p.x<x+w&&p.y>=y&&p.y<y+h)g.strokeRect((p.x-x)*8+1,(p.y-y)*8+1,6,6)}
 for(const b of $('modes').children){b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode))}
 $('patches').replaceChildren();const[x,y,w,h]=reg.crop;const list=meta.patches.filter(p=>p.x>=x&&p.x<x+w&&p.y>=y&&p.y<y+h);if(!list.length)$('patches').textContent='В этом участке предложений нет.';for(const p of list){const l=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.checked=!disabled.has(p.id);c.dataset.patch=p.id;c.onchange=()=>{if(c.checked)disabled.delete(p.id);else disabled.add(p.id);render()};l.append(c,`Цвет края · ${p.x}, ${p.y}`);$('patches').append(l)}
}
async function start(){const r=await fetch('assets/manifest.json');if(!r.ok)throw Error('manifest');meta=await r.json();for(const r of meta.regions)crops[r.id]={name:r.name,crop:r.crop};for(const[id,r]of Object.entries(crops)){const o=document.createElement('option');o.value=id;o.textContent=r.name;$('region').append(o)}
 await Promise.all(Object.entries({nearest:'assets/nearest.png',weak:'assets/weak.png',source:'assets/source.jpeg',cutout:'assets/cutout-preview.png'}).map(async([id,url])=>{images[id]=await load(url);if(['nearest','weak'].includes(id)){ctx.clearRect(0,0,139,208);ctx.drawImage(images[id],0,0);variants[id]=ctx.getImageData(0,0,139,208).data}}));
 for(const b of $('modes').children)b.onclick=()=>{mode=b.dataset.mode;render()};for(const id of ['region','reference','marks'])$(id).onchange=render;$('background').onchange=()=>document.body.className=$('background').value;$('restore').onclick=()=>{disabled.clear();render()};$('save').disabled=false;$('save').onclick=()=>result.toBlob(blob=>{if(!blob)return;const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`kat-white-dress-${mode}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)},'image/png');render();document.body.dataset.ready='true'}
start().catch(e=>{$('status').textContent='Не удалось загрузить сравнение. Обнови страницу.';console.error(e)});
