import {applyPatches} from './compose.mjs';
const $=id=>document.getElementById(id);let meta,base,source,mode='outline',disabled=new Set();
const result=document.createElement('canvas');result.width=139;result.height=208;
const ctx=result.getContext('2d');
function image(url){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=url})}
function drawCrop(canvas,img,crop,sourceImage=false){const [x,y,w,h]=crop;canvas.width=26*8;canvas.height=63*8;const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;const scale=Math.min(canvas.width/w,canvas.height/h);const sx=sourceImage?img.width/139:1,sy=sourceImage?img.height/208:1;c.drawImage(img,x*sx,y*sy,w*sx,h*sy,(canvas.width-w*scale)/2,(canvas.height-h*scale)/2,w*scale,h*scale)}
function render(){const out=applyPatches(base,meta,mode,disabled);ctx.putImageData(new ImageData(out,139,208),0,0);const whole=$('whole').getContext('2d');whole.clearRect(0,0,139,208);whole.drawImage(result,0,0);
 const reg=meta.regions.find(r=>r.id===$('region').value);const useSource=$('reference').value==='source';const temp=document.createElement('canvas');temp.width=139;temp.height=208;temp.getContext('2d').putImageData(new ImageData(base,139,208),0,0);drawCrop($('before'),useSource?source:temp,reg.crop,useSource);drawCrop($('after'),result,reg.crop);$('before-label').textContent=useSource?'Большой исходник':'Слабый PixelOE';
 let shape=0,color=0;const changed=[];for(let i=0;i<out.length;i+=4)if(out.slice(i,i+4).some((v,k)=>v!==base[i+k])){if(out[i+3]!==base[i+3])shape++;else color++;changed.push(i/4)}
 if($('marks').checked){const c=$('after').getContext('2d'),[x,y,w,h]=reg.crop,s=Math.min(208/w,504/h),ox=(208-w*s)/2,oy=(504-h*s)/2;for(const p of changed){const px=p%139,py=Math.floor(p/139);if(px<x||px>=x+w||py<y||py>=y+h)continue;const i=p*4;c.strokeStyle=out[i+3]!==base[i+3]?(out[i+3]?'#00d6ff':'#ff52bd'):'#ffcf32';c.lineWidth=2;c.strokeRect(ox+(px-x)*s+1,oy+(py-y)*s+1,s-2,s-2)}}
 $('status').textContent=`Силуэт: ${shape} пикс. · цвет края: ${color} пикс. по обеим икрам`;
 for(const b of $('modes').children){b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode))}
 $('patches').replaceChildren();const [x,y,w,h]=reg.bounds;for(const p of meta.patches.filter(p=>p.x>=x&&p.x<x+w&&p.y>=y&&p.y<y+h&&(mode==='both'||p.kind===mode))){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=!disabled.has(p.id);input.dataset.patch=p.id;input.onchange=()=>{if(input.checked)disabled.delete(p.id);else disabled.add(p.id);render()};label.append(input,`${p.kind==='outline'?'Цвет края':p.after[3]?'Добавить пиксель':'Убрать пиксель'} · ${p.x}, ${p.y}`);$('patches').append(label)}
 if(!$('patches').children.length)$('patches').textContent='Для этого участка в выбранном режиме правок нет.';
}
async function start(){const res=await fetch('patches.json');if(!res.ok)throw Error('patches');meta=await res.json();const [weak,original]=await Promise.all([image('../hybrid/assets/weak.png'),image('../png-lab/assets/kat-original.png')]);source=original;ctx.drawImage(weak,0,0);base=ctx.getImageData(0,0,139,208).data;
 for(const b of $('modes').children)b.onclick=()=>{mode=b.dataset.mode;render()};for(const id of ['region','reference','marks'])$(id).onchange=render;$('background').onchange=()=>document.body.className=$('background').value;$('restore').onclick=()=>{disabled.clear();render()};$('save').disabled=false;$('save').onclick=()=>result.toBlob(blob=>{if(!blob)return;const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`kat-weak-contour-${mode}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)},'image/png');render();document.body.dataset.ready='true'}
start().catch(e=>{$('status').textContent='Не удалось загрузить картинку. Попробуй обновить страницу.';console.error(e)});
